/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Client = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'address' : IDL.Text,
  'contactDetails' : IDL.Text,
});
export const LedgerEntry = IDL.Record({
  'clientId' : IDL.Nat,
  'description' : IDL.Text,
  'runningBalance' : IDL.Float64,
  'amount' : IDL.Float64,
});
export const ProductSpec = IDL.Record({
  'printingSide' : IDL.Text,
  'size' : IDL.Text,
  'productType' : IDL.Text,
  'lamination' : IDL.Text,
  'foiling' : IDL.Bool,
  'spotUV' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'defaultQuotationQuantity' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'productSpec' : ProductSpec,
  'details' : IDL.Text,
  'quantity' : IDL.Nat,
});
export const Quotation = IDL.Record({
  'id' : IDL.Nat,
  'paperGSM' : IDL.Text,
  'clientId' : IDL.Nat,
  'paperType' : IDL.Text,
  'pricePerUnit' : IDL.Float64,
  'productSpec' : ProductSpec,
  'approved' : IDL.Bool,
  'quantity' : IDL.Nat,
  'pages' : IDL.Nat,
  'bindingType' : IDL.Text,
  'price' : IDL.Float64,
  'totalPrice' : IDL.Float64,
  'laminationType' : IDL.Text,
  'pageNumbering' : IDL.Bool,
  'product' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BillSummary = IDL.Record({
  'gstAmount' : IDL.Float64,
  'totalAmount' : IDL.Float64,
  'ledgerEntry' : LedgerEntry,
  'subtotal' : IDL.Float64,
});
export const UserProfile = IDL.Record({
  'username' : IDL.Text,
  'name' : IDL.Text,
});
export const CompanyLogo = IDL.Record({
  'mimeType' : IDL.Text,
  'bytes' : IDL.Vec(IDL.Nat8),
});
export const CompanySettings = IDL.Record({
  'cin' : IDL.Text,
  'pan' : IDL.Text,
  'logo' : IDL.Opt(CompanyLogo),
  'placeOfWork' : IDL.Text,
  'addressLine1' : IDL.Text,
  'addressLine2' : IDL.Text,
  'addressLine3' : IDL.Text,
  'gstin' : IDL.Text,
  'address' : IDL.Text,
  'companyName' : IDL.Text,
  'gstRate' : IDL.Float64,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Client], []),
  'addLedgerEntry' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Float64],
      [LedgerEntry],
      [],
    ),
  'addProduct' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Product],
      [],
    ),
  'approveQuotation' : IDL.Func([IDL.Nat, IDL.Bool], [Quotation], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createBill' : IDL.Func([IDL.Nat], [BillSummary], []),
  'createQuotation' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Float64,
        IDL.Float64,
      ],
      [Quotation],
      [],
    ),
  'deleteClient' : IDL.Func([IDL.Nat], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getAllQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
  'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
  'getLedgerEntries' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getQuotation' : IDL.Func([IDL.Nat], [Quotation], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'updateClient' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
      [Client],
      [],
    ),
  'updateCompanySettings' : IDL.Func([CompanySettings], [], []),
  'updateProduct' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Bool,
        IDL.Bool,
        IDL.Nat,
        IDL.Float64,
        IDL.Nat,
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Text),
      ],
      [Product],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Client = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'address' : IDL.Text,
    'contactDetails' : IDL.Text,
  });
  const LedgerEntry = IDL.Record({
    'clientId' : IDL.Nat,
    'description' : IDL.Text,
    'runningBalance' : IDL.Float64,
    'amount' : IDL.Float64,
  });
  const ProductSpec = IDL.Record({
    'printingSide' : IDL.Text,
    'size' : IDL.Text,
    'productType' : IDL.Text,
    'lamination' : IDL.Text,
    'foiling' : IDL.Bool,
    'spotUV' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'defaultQuotationQuantity' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'productSpec' : ProductSpec,
    'details' : IDL.Text,
    'quantity' : IDL.Nat,
  });
  const Quotation = IDL.Record({
    'id' : IDL.Nat,
    'paperGSM' : IDL.Text,
    'clientId' : IDL.Nat,
    'paperType' : IDL.Text,
    'pricePerUnit' : IDL.Float64,
    'productSpec' : ProductSpec,
    'approved' : IDL.Bool,
    'quantity' : IDL.Nat,
    'pages' : IDL.Nat,
    'bindingType' : IDL.Text,
    'price' : IDL.Float64,
    'totalPrice' : IDL.Float64,
    'laminationType' : IDL.Text,
    'pageNumbering' : IDL.Bool,
    'product' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BillSummary = IDL.Record({
    'gstAmount' : IDL.Float64,
    'totalAmount' : IDL.Float64,
    'ledgerEntry' : LedgerEntry,
    'subtotal' : IDL.Float64,
  });
  const UserProfile = IDL.Record({ 'username' : IDL.Text, 'name' : IDL.Text });
  const CompanyLogo = IDL.Record({
    'mimeType' : IDL.Text,
    'bytes' : IDL.Vec(IDL.Nat8),
  });
  const CompanySettings = IDL.Record({
    'cin' : IDL.Text,
    'pan' : IDL.Text,
    'logo' : IDL.Opt(CompanyLogo),
    'placeOfWork' : IDL.Text,
    'addressLine1' : IDL.Text,
    'addressLine2' : IDL.Text,
    'addressLine3' : IDL.Text,
    'gstin' : IDL.Text,
    'address' : IDL.Text,
    'companyName' : IDL.Text,
    'gstRate' : IDL.Float64,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addClient' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [Client], []),
    'addLedgerEntry' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Float64],
        [LedgerEntry],
        [],
      ),
    'addProduct' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Product],
        [],
      ),
    'approveQuotation' : IDL.Func([IDL.Nat, IDL.Bool], [Quotation], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createBill' : IDL.Func([IDL.Nat], [BillSummary], []),
    'createQuotation' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Float64,
          IDL.Float64,
        ],
        [Quotation],
        [],
      ),
    'deleteClient' : IDL.Func([IDL.Nat], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllClients' : IDL.Func([], [IDL.Vec(Client)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getAllQuotations' : IDL.Func([], [IDL.Vec(Quotation)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClient' : IDL.Func([IDL.Nat], [Client], ['query']),
    'getCompanySettings' : IDL.Func([], [IDL.Opt(CompanySettings)], ['query']),
    'getLedgerEntries' : IDL.Func([IDL.Nat], [IDL.Vec(LedgerEntry)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getQuotation' : IDL.Func([IDL.Nat], [Quotation], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'updateClient' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, IDL.Text],
        [Client],
        [],
      ),
    'updateCompanySettings' : IDL.Func([CompanySettings], [], []),
    'updateProduct' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Bool,
          IDL.Bool,
          IDL.Nat,
          IDL.Float64,
          IDL.Nat,
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Text),
        ],
        [Product],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };