/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BillSummary {
  'gstAmount' : number,
  'totalAmount' : number,
  'ledgerEntry' : LedgerEntry,
  'subtotal' : number,
}
export interface Client {
  'id' : bigint,
  'name' : string,
  'address' : string,
  'contactDetails' : string,
}
export interface CompanyLogo { 'mimeType' : string, 'bytes' : Uint8Array }
export interface CompanySettings {
  'logo' : [] | [CompanyLogo],
  'gstin' : string,
  'address' : string,
  'companyName' : string,
  'gstRate' : number,
}
export interface LedgerEntry {
  'clientId' : bigint,
  'description' : string,
  'runningBalance' : number,
  'amount' : number,
}
export interface Product {
  'id' : bigint,
  'defaultQuotationQuantity' : bigint,
  'name' : string,
  'description' : string,
  'pricePerUnit' : number,
  'productSpec' : ProductSpec,
  'details' : string,
  'quantity' : bigint,
}
export interface ProductSpec {
  'printingSide' : string,
  'size' : string,
  'productType' : string,
  'lamination' : string,
  'foiling' : boolean,
  'spotUV' : boolean,
}
export interface Quotation {
  'id' : bigint,
  'paperGSM' : string,
  'clientId' : bigint,
  'paperType' : string,
  'pricePerUnit' : number,
  'productSpec' : ProductSpec,
  'approved' : boolean,
  'quantity' : bigint,
  'pages' : bigint,
  'bindingType' : string,
  'price' : number,
  'totalPrice' : number,
  'laminationType' : string,
  'pageNumbering' : boolean,
  'product' : string,
}
export interface UserProfile { 'username' : string, 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addClient' : ActorMethod<[string, string, string], Client>,
  'addLedgerEntry' : ActorMethod<[bigint, string, number], LedgerEntry>,
  'addProduct' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      bigint,
      number,
      bigint,
      [] | [string],
      [] | [string],
    ],
    Product
  >,
  'approveQuotation' : ActorMethod<[bigint, boolean], Quotation>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createBill' : ActorMethod<[bigint], BillSummary>,
  'createQuotation' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      bigint,
      string,
      string,
      boolean,
      string,
      string,
      bigint,
      number,
      number,
    ],
    Quotation
  >,
  'deleteClient' : ActorMethod<[bigint], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllClients' : ActorMethod<[], Array<Client>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getAllQuotations' : ActorMethod<[], Array<Quotation>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClient' : ActorMethod<[bigint], Client>,
  'getCompanySettings' : ActorMethod<[], [] | [CompanySettings]>,
  'getLedgerEntries' : ActorMethod<[bigint], Array<LedgerEntry>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getQuotation' : ActorMethod<[bigint], Quotation>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateClient' : ActorMethod<[bigint, string, string, string], Client>,
  'updateCompanySettings' : ActorMethod<[CompanySettings], undefined>,
  'updateProduct' : ActorMethod<
    [
      bigint,
      string,
      string,
      string,
      string,
      string,
      boolean,
      boolean,
      bigint,
      number,
      bigint,
      [] | [string],
      [] | [string],
    ],
    Product
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];