/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface ProductSpec {
    printingSide: string;
    size: string;
    productType: string;
    lamination: string;
    foiling: boolean;
    spotUV: boolean;
}
export interface Quotation {
    id: bigint;
    paperGSM: string;
    clientId: bigint;
    paperType: string;
    pricePerUnit: number;
    productSpec: ProductSpec;
    approved: boolean;
    quantity: bigint;
    pages: bigint;
    bindingType: string;
    price: number;
    totalPrice: number;
    laminationType: string;
    pageNumbering: boolean;
    product: string;
}
export interface CompanyLogo {
    mimeType: string;
    bytes: Uint8Array;
}
export interface CompanySettings {
    cin: string;
    pan: string;
    logo?: CompanyLogo;
    placeOfWork: string;
    addressLine1: string;
    addressLine2: string;
    addressLine3: string;
    gstin: string;
    address: string;
    companyName: string;
    gstRate: number;
}
export interface BillSummary {
    gstAmount: number;
    totalAmount: number;
    ledgerEntry: LedgerEntry;
    subtotal: number;
}
export interface Client {
    id: bigint;
    name: string;
    address: string;
    contactDetails: string;
}
export interface LedgerEntry {
    clientId: bigint;
    description: string;
    runningBalance: number;
    amount: number;
}
export interface Product {
    id: bigint;
    defaultQuotationQuantity: bigint;
    name: string;
    description: string;
    pricePerUnit: number;
    productSpec: ProductSpec;
    details: string;
    quantity: bigint;
}
export interface UserProfile {
    username: string;
    name: string;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addClient(name: string, contactDetails: string, address: string): Promise<Client>;
    addLedgerEntry(clientId: bigint, description: string, amount: number): Promise<LedgerEntry>;
    addProduct(name: string, productType: string, size: string, printingSide: string, lamination: string, spotUV: boolean, foiling: boolean, defaultQuotationQuantity: bigint, pricePerUnit: number, quantity: bigint, description: string | null, details: string | null): Promise<Product>;
    approveQuotation(id: bigint, approved: boolean): Promise<Quotation>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createBill(quotationId: bigint): Promise<BillSummary>;
    createQuotation(clientId: bigint, product: string, productType: string, size: string, printingSide: string, lamination: string, spotUV: boolean, foiling: boolean, pages: bigint, paperType: string, paperGSM: string, pageNumbering: boolean, laminationType: string, bindingType: string, quantity: bigint, price: number, pricePerUnit: number): Promise<Quotation>;
    deleteClient(id: bigint): Promise<void>;
    deleteProduct(id: bigint): Promise<void>;
    getAllClients(): Promise<Array<Client>>;
    getAllProducts(): Promise<Array<Product>>;
    getAllQuotations(): Promise<Array<Quotation>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClient(id: bigint): Promise<Client>;
    getCompanySettings(): Promise<CompanySettings | null>;
    getLedgerEntries(clientId: bigint): Promise<Array<LedgerEntry>>;
    getProduct(id: bigint): Promise<Product>;
    getQuotation(id: bigint): Promise<Quotation>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    updateClient(id: bigint, name: string, contactDetails: string, address: string): Promise<Client>;
    updateCompanySettings(settings: CompanySettings): Promise<void>;
    updateProduct(id: bigint, name: string, productType: string, size: string, printingSide: string, lamination: string, spotUV: boolean, foiling: boolean, defaultQuotationQuantity: bigint, pricePerUnit: number, quantity: bigint, description: string | null, details: string | null): Promise<Product>;
}
import type { CompanyLogo as _CompanyLogo, CompanySettings as _CompanySettings, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addClient(arg0: string, arg1: string, arg2: string): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.addClient(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addClient(arg0, arg1, arg2);
            return result;
        }
    }
    async addLedgerEntry(arg0: bigint, arg1: string, arg2: number): Promise<LedgerEntry> {
        if (this.processError) {
            try {
                const result = await this.actor.addLedgerEntry(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addLedgerEntry(arg0, arg1, arg2);
            return result;
        }
    }
    async addProduct(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: boolean, arg6: boolean, arg7: bigint, arg8: number, arg9: bigint, arg10: string | null, arg11: string | null): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg11));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg10), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg11));
            return result;
        }
    }
    async approveQuotation(arg0: bigint, arg1: boolean): Promise<Quotation> {
        if (this.processError) {
            try {
                const result = await this.actor.approveQuotation(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.approveQuotation(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n2(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createBill(arg0: bigint): Promise<BillSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.createBill(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBill(arg0);
            return result;
        }
    }
    async createQuotation(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean, arg7: boolean, arg8: bigint, arg9: string, arg10: string, arg11: boolean, arg12: string, arg13: string, arg14: bigint, arg15: number, arg16: number): Promise<Quotation> {
        if (this.processError) {
            try {
                const result = await this.actor.createQuotation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createQuotation(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11, arg12, arg13, arg14, arg15, arg16);
            return result;
        }
    }
    async deleteClient(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClient(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async getAllClients(): Promise<Array<Client>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllClients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllClients();
            return result;
        }
    }
    async getAllProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProducts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProducts();
            return result;
        }
    }
    async getAllQuotations(): Promise<Array<Quotation>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllQuotations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllQuotations();
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClient(arg0: bigint): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.getClient(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClient(arg0);
            return result;
        }
    }
    async getCompanySettings(): Promise<CompanySettings | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCompanySettings();
                return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCompanySettings();
            return from_candid_opt_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLedgerEntries(arg0: bigint): Promise<Array<LedgerEntry>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLedgerEntries(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLedgerEntries(arg0);
            return result;
        }
    }
    async getProduct(arg0: bigint): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return result;
        }
    }
    async getQuotation(arg0: bigint): Promise<Quotation> {
        if (this.processError) {
            try {
                const result = await this.actor.getQuotation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getQuotation(arg0);
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async updateClient(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<Client> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClient(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClient(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateCompanySettings(arg0: CompanySettings): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateCompanySettings(to_candid_CompanySettings_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateCompanySettings(to_candid_CompanySettings_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProduct(arg0: bigint, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: boolean, arg7: boolean, arg8: bigint, arg9: number, arg10: bigint, arg11: string | null, arg12: string | null): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg12));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProduct(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, to_candid_opt_n1(this._uploadFile, this._downloadFile, arg11), to_candid_opt_n1(this._uploadFile, this._downloadFile, arg12));
            return result;
        }
    }
}
function from_candid_CompanySettings_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CompanySettings): CompanySettings {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanyLogo]): CompanyLogo | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_CompanySettings]): CompanySettings | null {
    return value.length === 0 ? null : from_candid_CompanySettings_n8(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cin: string;
    pan: string;
    logo: [] | [_CompanyLogo];
    placeOfWork: string;
    addressLine1: string;
    addressLine2: string;
    addressLine3: string;
    gstin: string;
    address: string;
    companyName: string;
    gstRate: number;
}): {
    cin: string;
    pan: string;
    logo?: CompanyLogo;
    placeOfWork: string;
    addressLine1: string;
    addressLine2: string;
    addressLine3: string;
    gstin: string;
    address: string;
    companyName: string;
    gstRate: number;
} {
    return {
        cin: value.cin,
        pan: value.pan,
        logo: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.logo)),
        placeOfWork: value.placeOfWork,
        addressLine1: value.addressLine1,
        addressLine2: value.addressLine2,
        addressLine3: value.addressLine3,
        gstin: value.gstin,
        address: value.address,
        companyName: value.companyName,
        gstRate: value.gstRate
    };
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function to_candid_CompanySettings_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CompanySettings): _CompanySettings {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cin: string;
    pan: string;
    logo?: CompanyLogo;
    placeOfWork: string;
    addressLine1: string;
    addressLine2: string;
    addressLine3: string;
    gstin: string;
    address: string;
    companyName: string;
    gstRate: number;
}): {
    cin: string;
    pan: string;
    logo: [] | [_CompanyLogo];
    placeOfWork: string;
    addressLine1: string;
    addressLine2: string;
    addressLine3: string;
    gstin: string;
    address: string;
    companyName: string;
    gstRate: number;
} {
    return {
        cin: value.cin,
        pan: value.pan,
        logo: value.logo ? candid_some(value.logo) : candid_none(),
        placeOfWork: value.placeOfWork,
        addressLine1: value.addressLine1,
        addressLine2: value.addressLine2,
        addressLine3: value.addressLine3,
        gstin: value.gstin,
        address: value.address,
        companyName: value.companyName,
        gstRate: value.gstRate
    };
}
function to_candid_variant_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
